# Generated by Django 3.1 on 2020-11-18 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('repuesto', '0002_auto_20201104_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad de repuestos')),
                ('subtotal', models.IntegerField(verbose_name='Subtotal a pagar')),
                ('repuesto', models.ManyToManyField(to='repuesto.Repuesto', verbose_name='Repuestos')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
                'db_table': 'detalleventa',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de venta')),
                ('formapago', models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Tarjeta de debito'), ('credito', 'Tarjeta de credito')], max_length=20, verbose_name='Forma de pago')),
                ('total', models.IntegerField(verbose_name='Total a pagar')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Cliente')),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.detalleventa', verbose_name='Detalles de venta')),
            ],
        ),
    ]
