# Generated by Django 3.1 on 2020-11-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20201118_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='subtotal',
            field=models.CharField(max_length=6, verbose_name='Subtotal a pagar'),
        ),
    ]
