# Generated by Django 3.1 on 2020-11-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_auto_20201118_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='subtotal',
            field=models.IntegerField(verbose_name='Subtotal a pagar'),
        ),
    ]
