# Generated by Django 3.1 on 2020-11-05 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('repuesto', '0002_auto_20201104_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleReparacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repuesto', models.ManyToManyField(to='repuesto.Repuesto', verbose_name='Reparaciones')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
                'db_table': 'detallereparacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de entrega(aprox)')),
                ('precio', models.CharField(max_length=6, verbose_name='Precio')),
                ('detalle_reparacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reparacion.detallereparacion', verbose_name='Detalle de reparacion')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.solicitud', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Reparacion',
                'verbose_name_plural': 'Reparaciones',
                'db_table': 'reparacion',
                'ordering': ['id'],
            },
        ),
    ]
