# Generated by Django 3.1 on 2020-11-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_repuesto', models.CharField(max_length=30, verbose_name='Nombre del Repuesto')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('imagen', models.ImageField(upload_to='Repuesto', verbose_name='Imagen del repuesto')),
                ('estado', models.BooleanField(default=True, verbose_name='Activado/Desactivado')),
                ('creado', models.DateField(auto_now_add=True)),
                ('editado', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
                'db_table': 'repuesto',
                'ordering': ['id'],
            },
        ),
    ]
