# Generated by Django 3.1 on 2020-11-05 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repuesto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuesto',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='editado',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='estado',
        ),
    ]
